name: adguard_home_manager
description: AdGuard Home client
publish_to: 'none'
version: 2.22.0+154

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.5
  sqflite: ^2.4.2
  package_info_plus: ^8.0.0
  dynamic_color: ^1.8.1
  animations: ^2.1.0
  device_info_plus: ^11.2.1
  uuid: ^4.5.1
  expandable: ^5.0.1
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.1
  percent_indicator: ^4.2.5
  flutter_markdown: ^0.7.7+1
  markdown: ^7.3.0
  html: ^0.15.6
  flutter_html: ^3.0.0
  sqlite3_flutter_libs: ^0.5.40
  sqflite_common_ffi: ^2.3.6
  contextmenu: ^3.0.0
  async: ^2.13.0
  sentry_flutter: ^9.7.0
  flutter_dotenv: ^6.0.0
  flutter_reorderable_list: ^1.3.1
  pie_chart: ^5.4.0
  segmented_button_slide: ^2.0.0
  http: ^1.5.0
  timezone: ^0.10.1
  flutter_custom_tabs: ^2.4.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_gen: ^5.12.0

dependency_overrides:
  vector_math: ^2.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon-ios.png
    - assets/icon/icon-android-adap.png
    - assets/icon/icon-android.png
    - assets/icon/icon-splash.png
    - assets/icon/icon-macos.png
    - assets/icon/icon-circle.png
    - assets/icon/icon-circle-256.png
    - assets/icon/icon1024-white-center.png
    - assets/other/get_google_play.png
    - assets/resources/github.svg
    - assets/resources/google-play.svg
    - .env
